name: avatar_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  provider: ^6.1.2
  file_picker: ^9.0.2
  audioplayers: ^6.3.0
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
