name: avatar_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  provider: ^6.1.2
  file_picker: ^9.2.1
  audioplayers: ^6.4.0
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.2.2
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.1.2
  window_manager: ^0.3.4
  msix: ^3.16.8
  idb_shim: ^2.6.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/app_icons/

msix_config:
  display_name: Voice Avatar Hub
  publisher_display_name: Your Company Name
  identity_name: com.yourcompany.voiceavatarhub
  msix_version: 1.0.0.0
  logo_path: assets/app_icons/app_icon_256.png
  capabilities: internetClient
  languages: en-us
  architecture: x64
  store: false
  execution_alias: VoiceAvatarHub
  app_installer:
    publish_folder_path: C:\MSIX\
    hours_between_update_checks: 0
    automatic_background_task: false
    update_blocks_activation: false
    show_prompt: true
    force_update_from_any_version: false
